author = "ares0x"
description = "Less is more."

[[params.social]]
  name = "github"
  url = "https://github.com/ares0x"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"


baseURL = "ares0x.github.io"
languageCode = "en-us"
title = "Ares's Blog"
